name: flutter_gpiod
description:
  Dart package for accessing GPIO using the GPIO character device interface on linux / Android (root required).
  Supports signal edge listening, active state, open source/drain and (if supported by platform) bias.
version: 0.3.2
homepage: https://ardera.dev/
repository: https://github.com/ardera/flutter_gpiod
   
environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  ffi: ^1.0.0
  tuple: ^2.0.0
  path: ^1.7.0
